/**
 * IconName is a list of all the icons in the game.
 * can be used to render UI via IconFactory
 */
export enum IconName {
  // keywords
  CLEVER = 'Clever',
  SUN_BATHING = 'Sun Bathing',
  POUCH = 'Pouch',
  HUNTER = 'Hunter',
  SPRINT = 'Sprint',
  PACK = 'Pack',
  JUMPING = 'Jumping',
  INVENTIVE = 'Inventive',
  INVENTIVE_BEAR = 'Inventive: Bear',
  INVENTIVE_PRIMARY = 'Inventive: Primary',
  BOOST_ASSOCIATION = 'Boost: Association',
  BOOST_BUILDING = 'Boost: Building',
  BOOST_CARD = 'Boost: Card',
  BOOST_SPONSORS = 'Boost: Sponsors',
  BOOST_ANIMAL = 'Boost: Animal',
  ACTION_ASSOCIATION = 'Action: Association',
  ACTION_BUILDING = 'Action: Building',
  ACTION_CARDS = 'Action: Cards',
  ACTION_SPONSORS = 'Action: Sponsors',
  ACTION_ANIMAL = 'Action: Animal',
  MULTIPLIER_ASSOCIATION = 'Multiplier: Association',
  MULTIPLIER_BUILDING = 'Multiplier: Building',
  MULTIPLIER_CARD = 'Multiplier: Card',
  MULTIPLIER_SPONSORS = 'Multiplier: Sponsors',
  MULTIPLIER_ANIMAL = 'Multiplier: Animal',
  FULL_THROATED = 'Full-throated',
  ICONIC_ANIMAL = 'Iconic Animal',
  RESISTANCE = 'Resistance',
  ASSERTION = 'Assertion',
  DIGGING = 'Digging',
  SPONSOR_MAGNET = 'Sponsor Magnet',
  FLOCK_ANIMAL = 'Flock Animal',
  DOMINANCE = 'Dominance',
  PILFERING_1 = 'Pilfering 1',
  PILFERING_2 = 'Pilfering 2',
  SNAPPING = 'Snapping',
  SNAPPING_1 = 'Snapping 1',
  SNAPPING_2 = 'Snapping 2',
  VENOM = 'Venom',
  CONSTRICTION = 'Constriction',
  HYPNOSIS = 'Hypnosis',
  SCAVENGING = 'Scavenging',
  POSTURING = 'Posturing',
  PERCEPTION_2 = 'Perception 2',
  PERCEPTION_4 = 'Perception 4',
  DETERMINATION = 'Determination',
  PEACOCKING = 'Peacocking',
  PETTING_ZOO_ANIMAL = 'Petting Zoo Animal',
  MARK = 'Mark',
  TRADE = 'Trade',
  SEA_ANIMAL_MAGNET = 'Sea Animal Magnet',
  REEF_MONEY = 'Money',
  SYMBIOSIS = 'Symbiosis',
  HELPFUL = 'Helpful',
  TAKE_CARD_IN_RANGE = 'Take Card in Range',
  REPUTATION = 'Reputation',
  EXTRA_SHIFT = 'Extra Shift',
  GLIDE = 'Glide',
  SHARK_ATTACK = 'Shark Attack',
  CUT_DOWN = 'Cut Down',
  CAMOUFLAGE = 'Camouflage',
  SCUBA_DIVE = 'Scuba Dive X',
  MARKETING = 'Marketing',
  ADAPT = 'Adapt',
  MONKEY_GANG = 'Monkey Gang',
  WATER_AFFINITY = 'Water Affinity',

  // game components
  SIZE = 'Size',
  X_TOKEN = 'X Token',
  MONEY = 'Money',
  SLOT = 'Slot',
  APPEAL = 'Appeal',
  CONSERVATION_POINT = 'Conservation Point',
  MULTIPLIER_TOKEN = 'Multiplier Token',

  // tag
  HERBIVORE = 'Herbivore',
  REPTILE = 'Reptile',
  SEA_ANIMAL = 'Sea Animal',
  PRIMATE = 'Primate',
  BIRD = 'Bird',
  SCIENCE = 'Science',
  ROCK = 'Rock',
  WATER = 'Water',

  // actionCard
  ACTION_CARD = 'Action Card',
  ASSOCIATION_ACTION_CARD = 'Association Action Card',
  ANIMAL_ACTION_CARD = 'Animal Action Card',
  BUILD_ACTION_CARD = 'Build Action Card',
  CARDS_ACTION_CARD = 'Cards Action Card',
  SPONSORS_ACTION_CARD = 'Sponsors Action Card',

  // buildings
  LARGE_BIRD_AVIARY = 'Large Bird Aviary',
  KIOSK = 'Kiosk',

  // endgames

  EMPTY_ENCLOSURE = 'Empty Enclosure',
  SPONSOR_CARD = 'Sponsor Card',
  CONSERVATION_PROJECT = 'Conservation Project',
  ANIMAL_CATEGORIES = 'Animal Categories',
  CONTINENT_CATEGORIES = 'Continent Categories',
  DIFFERENT_SHAPE = 'Different Shape',
  ONE_ANIMAL_TAG = 'One Animal Tag',
  ONE_CONTINENT_TAG = 'One Continent Tag',
  ONE_TAG = 'One Tag',
  KIOSK_PAVILION_PAIR = 'Kiosk and Pavilion Pair',
  CONDITION = 'Condition',
  ICONS_COMPARE_WITH_PLAYER = 'Icons Compare with Player',
}
