name: Manually Triggered API Call

on:
  workflow_dispatch: # 添加手动触发功能

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call API
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "X-API-Key: \${{ secrets.DAILY_QUIZ_API }}" \
          -d '{"gameConfig": {"cardSources": ["Base", "Marine World", "Promo"], "mapSources": ["Base", "Alternative", "Promo"], "mode": "default", "players": 2}}' \
          https://ark-nova.ender-wiggin.com/api/quiz/create